### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by jojoyee** [willbelr/qtpad#1]
On the line 165 of "qtpad.py", it experienced a syntax error as follows:

File "qtpad.py", line 165
    self.style = self.exec()
                         ^
SyntaxError: invalid syntax

**Comment by willbelr** [comment]
I think the error is caused by the version of your python interpreter, as the script was only tested using the lastest (3.6 as of now). For instance, 'exec' was a keyword in python2, and then became a built in function in python3. I updated qtpad.py by replacing all calls to 'exec' with 'exec_'. Hopefully that will work. Else please try to update your python version.

If it still does not work, please let me know what version and OS you are using so I can try to replicate the problem.
